package com.task.beans.rbac;

public enum PrivilegeEnum {

	USER_WHO_CAN_GET_ALL_USERS, USER_WHO_CAN_GET_ALL_ACCOUNTS , USER_WHO_CAN_GET_ALL_FARMS , USER_WHO_CAN_GET_ALL_FARMS_FROM_ALL_USERS, USER_WHO_CAN_GET_ALL_CUSTOMERS

}
